google/cargo-raze

- src/templates/crate.BUILD.template
Fixes https://github.com/acmcarther/cargo-raze/issues/30#issuecomment-365379349
Demoed in https://github.com/acmcarther/cargo-raze-examples/compare/demo-acm-fix-whitespace , which I'll push after pushing this change to Cargo.
> Fix whitespace for vendored targets

- Cargo.lock
- README.md
- src/bazel.rs
- src/main.rs
- src/templates/remote_crates.bzl.template
Two changes:
- Moved {workspace_path}/vendor/BUILD into {workspace_path}/BUILD
- Moved generated remote deps from {workspace_path}/... into {workspace_path}/remote/...
No logic changes were required for vendored deps, but I needed to change a bit for remote deps.
Generated Example: https://github.com/acmcarther/cargo-raze-examples/tree/acm-update-genfile-location-example/bazel. I'll update the repository "officially" to catch all the latest changes once this PR is submitted
> Update genfile location

- src/planning.rs
Partially resolves: https://github.com/acmcarther/cargo-raze/issues/27#issuecomment-370038069
https://github.com/google/cargo-raze/commits/use-cargo-metadata makes this obsolete but it requires a cargo release....
> Support './' in lib.path targets

- src/planning.rs
Found myself upgrading crates and not (quickly) noticing that overrides were no longer being applied.
Not sure if this should be a harder error, lmk if you'd like it done differently. The output is kind of noisy right now as well, which may make this hard to notice if you don't know to look for it.
> Complain to stderr about unused raze settings.

- src/license.rs
- src/planning.rs
- src/rendering.rs
- src/settings.rs
- src/util.rs
Somehow since the time I first wrote some of this code I've accreted more dogmatic opinions.
Some of those fixed here include:
1) Serde defaults should be of the form `default_{type}_field_{field_name}`
2) Files should be organized in the following manner:
```
// traits
// structs / enums
// impls
// bare fns
```
(I've judged that struct-struct proximity is more important than struct-impl or trait-impl proximity, since impls can live anywhere anyway).
Also it seems rustfmt found more things to fix...
> Minor code cleanup

- src/templates/partials/build_script.template
- src/templates/partials/remote_build_script.template
Fixes https://github.com/google/cargo-raze/issues/32
Probably will be broken in CI. Will fix.
> Add RUSTC as env_var to buildscripts

- impl/Cargo.lock
- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/settings.rs
- impl/src/templates/remote_crates.bzl.template
The SHA-256 is available from Cargo so it's easy to expose and it helps Bazel with caching and reproducibility.
This PR also contains 2 minor fixes:
- Update Cargo.lock, the current one fail on my machine (Ubuntu 18.04)
- Remove some unused variables and mark two modules as test config to remove unused warnings.
> Add SHA-256 to the local_repositories

- impl/src/templates/partials/build_script.template
- impl/src/templates/partials/remote_build_script.template
- impl/src/templates/partials/remote_rust_binary.template
- impl/src/templates/partials/remote_rust_library.template
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
- smoke-test.sh
Now that rust_library/rust_binary supports it.
> Add version number to imported crates

- impl/src/templates/remote_crates.bzl.template
Using native.existing_rules allow to use several crates.bzl file that
would import the same crates without failing with duplicate rules.
> Remote: do not create http repository if it already exists.

- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/templates/remote_crates.bzl.template
Previously the remote non-cratesio example worked because it accidentally resolved to crates.io even for "git" packages. The example was included before it was ready, and only because it relied exclusively on things already on `crates.io` did it compile in the first place.
Also takes a much lighter touch with metadata.rs - we know that we're checking out a git repository, so can guarantee that there's a `.git` folder somewhere when we walk back up the path, rather than relying on Cargo to tell us where the repo root is actually at.
---
Continues on from #31
> Take two on remote Git targets

- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/main.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/settings.rs
- impl/src/templates/partials/build_script.template
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
- impl/src/templates/remote_crates.bzl.template
- impl/src/templates/workspace.BUILD.template
- impl/src/util.rs
Breaks out the BuildPlannerImpl classes' responsibilities into a bunch of smaller planners which have reasonable scope. Removes weird hash maps. Adds CargoCrateCatalog and uses it to look up things.
This gives me a reasonable place from which to continue https://github.com/google/cargo-raze/pull/54 without having to keep a billion hashmaps and random blobs in my head.
EDIT:
This also renames and gently restructures some code I nitted but allowed through during review. Gotta have those incredibly long variable names or I let my Java heritage down. I hope nobody is offended.
> Clean up the planner code

- impl/src/templates/crate.BUILD.template
This rule is never used and was renamed in recent rust rules into
rust_bechmark.
> Remove rust_bench_test from generated imports

- impl/Cargo.lock
- impl/Cargo.toml
- impl/src/bazel.rs
- impl/src/main.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/util.rs
- smoke_test/vendored/non_cratesio_library/cargo/Cargo.toml
The largest change of consequence from this upgrade is that the error handling had to change a bunch because strings don't directly coerce to CargoError. I added a RazeError type for this purpose, but I didn't put much thought into it. 
Fixes https://github.com/google/cargo-raze/issues/66
CI is probably going to fail for some reason or other.
EDIT: Reminder to self -- this is going to need a release.
> Update dependencies and fix for cargo 0.30.0

- impl/src/templates/partials/build_script.template
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
Fixes https://github.com/google/cargo-raze/issues/69
The target setting is now being set (since https://github.com/bazelbuild/rules_rust/pull/136) by rules_rust internals and it is no longer appropriate for us to be setting it here. Per the current path we're taking for cross compilation, the toolchain itself is the only entity that knows the proper target setting. It has not yet been determined how the complation target will be set. Work and supplemental discussion is ongoing in https://github.com/google/cargo-raze/pull/54
The builds for this PR will be broken until https://github.com/google/cargo-raze/pull/67 is submitted (or a build containing the fix to the non_cratesio_library example.
> Remove rust_library.rustc_flag.target setting per rules_rust changes

- README.md
cargo-raze generates `cargo_fetch_remote_crates()` and not `raze_fetch_remote_crates()`
> README: correct name for generated cargo_fetch_remote_crates()

- impl/src/templates/remote_crates.bzl.template
* native.new_git_repository is replaced by the skylark
new_git_repository
* native.new_http_archive is replaced by the skylark http_archive
* Surround labels with the Label function so that crate.bzl can be
used from other repositories.
> Remote mode: use Label() and non native git/http.

- .travis.yml
- README.md
- smoke-test.sh
0.17 is the minimum version supported by rules_rust at this point.
Still unclear why Bazel build failures didn't cause a Travis failure (https://travis-ci.org/google/cargo-raze/builds/477524733). Maybe 0.11 doesn't return a bad exit code during loading phase failures?
> Bump Bazel on Travis to 0.17.1

- smoke-test.sh
- smoke_test/vendored/non_cratesio_library/cargo/Cargo.toml
Related: 
https://github.com/google/cargo-raze/pull/80
https://github.com/google/cargo-raze/pull/81
Waiting on #81 to finish and get submitted.
---
It seems smoke tests were broken in a variety of ways, some of which are really inexplicable:
1) **non_cratesio_library's futures dependency was plainly not compatible with the code.** It was trying to use a version of futures that didn't have functions it needed. CI for the PR that made the most recent changes passed, so perhaps we have some kind of caching issue?
2) **The workspace name for the example workspace was the same as rules_rust.** This apparently confuses Bazel greatly on newer versions of Bazel (but not older ones?)
3) Per the original PR name in smoke-test.sh **`bazel build X && bazel build Y` causes failures in the build of X …
> Fix Broken smoke-test.sh

- impl/Cargo.toml
- impl/src/bin/cargo-raze.rs
- impl/src/bin/dump_metadata.rs
- impl/src/lib.rs
- impl/src/metadata.rs
The docopt for this new binary
```
Loads and serializes metadata for a provided Cargo.toml
Usage:
dump_metadata <path-to-toml> [options]
Options:
-h, --help                  Print this message
--noinfer-lock-file         Disable inferring lock file from toml path
--pretty-print              Whether or not to pretty-print the output
--output-file=<path>        A filepath to print the generated output to
```
This PR adds a new bin to sit alongside the base "cargo-raze" bin. This binary generates metadata of the form that cargo-raze itself generates, and should be useful to help understand Cargo.toml files as cargo-raze understands them.
The binary is not intended to be used by end users. This PR adds a "cargo-raze" library to support the cargo-raze binary and this new dump_metadata binary, …
> Add dump_metadata bin for quickly producing serialized metadata

- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/planning.rs
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/workspace.BUILD.template
This PR also fixes an outstanding issue where multi-(output-)target crates whose lib target was not named after the crate would have the wrong lib dependency declared.
Also now omits root deps from alias BUILD file if the dep does not have a lib.
Fixes https://github.com/google/cargo-raze/issues/83
> Support binary dependencies that do not have associated libs

- impl/src/templates/workspace.BUILD.template
I'm not sure why I originally added this constraint, but I'll remove it and see if CI accepts it.
cc @mfarrugi
https://github.com/google/cargo-raze/issues/89
> Remove requirement for lib in crate for adding aliases

- impl/src/bazel.rs
- impl/src/bin/cargo-raze.rs
- impl/src/planning.rs
- impl/src/rendering.rs
- impl/src/settings.rs
- smoke-test.sh
- smoke_test/vendored/hello_cargo_library/cargo/Cargo.toml
Related issue: #92 
Default is BUILD
Other values can be for example: BUILD.bazel
Any value is accepted.
This is to follow the default behaviour of other bazel related tools
that generate BUILD.bazel instead of BUILD firstly to separate
what is generated and what is written and to avoid name collisions on
case insensitive file systems (Windows + WSL) since some crates can
have a directory named build which leads to cargo-raze unable to create
a file called BUILD. A project having a directory named BUILD.bazel is
much less likely or less to none chance.
How to use (example):
Add following to the `Cargo.toml` file
```
[raze]
output_buildfile_suffix = "BUILD.bazel"
```
I am still very new to Rust, and may have written something not idiomatic at all, and would appreciate any advice to make it …
> [settings] Add output_buildfile_suffix option

- impl/src/bin/cargo-raze.rs
- impl/src/planning.rs
Fixes https://github.com/google/cargo-raze/issues/42
In supporting "vendor into workspace root", there are two options. Fix the handling of bazel paths by introducing a Label type, implementing deserialization of labels and a Path api on them. **OR**, handle the corner case.
This PR does the latter. This is a perpetuation of terrible stringly typed label nonsense that was also observed earlier today in [this comment](https://github.com/google/cargo-raze/pull/94#issuecomment-487251750) on https://github.com/google/cargo-raze/pull/94. I need to introduce real types for these labels and identifiers instead of just juggling strings. 
I also need to refactor raze itself to better support tests. This change is *also* hard to test. Bonus difficulty: a smoke test can't even test this because …
> Support cargo-raze into "//"

- impl/src/planning.rs
- impl/src/templates/crate.BUILD.template
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
- impl/src/templates/remote_crates.bzl.template
- impl/src/util.rs
- smoke_test/remote/complicated_cargo_library/cargo/Cargo.lock
- smoke_test/remote/complicated_cargo_library/cargo/Cargo.toml
- smoke_test/vendored/complicated_cargo_library/cargo/Cargo.lock
- smoke_test/vendored/complicated_cargo_library/cargo/Cargo.toml
Not sure if it's WSL only, but mixed case crates has mixed case target
names, but they're only referred to with lowercase in deps.
This fixes the casing issue.
Example crate is `MacTypes_sys` which is a dependency of `security-framework-sys`.
Building that target would fail with `unknown target mactypes_sys` because the target was called `MacTypes_sys`
Not sure if this has something to do with WSL (case insensitive file system), but this seems to fix it.
If this approach is flawed I would greatly appreciate any feedback.
This also removes the unnecessary comment of unsupported kind.
Thanks.
EDIT:
This PR has drastically changed the approach to fixing this issue.
> [BUILD] Fix inconsistent casing in targets and dep targets

- impl/src/planning.rs
- impl/src/util.rs
Fixes https://github.com/google/cargo-raze/issues/111
Does not add any BUILD generation for workspace crates. This is a sensible next step if there are opinions about where those files should land.
> Ignore workspace crates when doing crate planning and vendor validation

- impl/src/planning.rs
This is a minor fix for #119, rather than edit the template (which seems to get fixed and unfixed) we allow the lib to be a proc-macro as well as an rlib
> [Planning] Allow proc-macros to export (#119)

- impl/src/metadata.rs
This addresses the panic described in https://github.com/google/cargo-raze/issues/139#issuecomment-594678552.
> Fix incorrect package source id String in CargoInternalsMetadataFetcher

- smoke-test.sh
This is required for bazel 3.1.0; otherwise
https://github.com/bazelbuild/bazel/issues/7793
causes build failures.
> [smoke-test] Update rules_rust version

- impl/src/bazel.rs
- impl/src/settings.rs
- impl/src/templates/partials/remote_crates_patch.template
- impl/src/templates/remote_crates.bzl.template
- smoke_test/remote/complicated_cargo_library/BUILD
- smoke_test/remote/complicated_cargo_library/cargo/Cargo.toml
- smoke_test/remote/complicated_cargo_library/cargo/libloading_global_static.BUILD
- smoke_test/remote/complicated_cargo_library/src/main.rs
This adds a new crate option `additional_build_file` for appending custom content to the generated
BUILD files. For example, to include custom Bazel targets for building non-Rust parts of a crate.
I started out with an option to completely override the BUILD file, but I think that's more trouble than it's worth maintenance-wise. So far I haven't needed to change anything Raze generates besides adding to it (e.g. `cc_library` targets).
@mfarrugi - have you run into any cases where this wouldn't be sufficient?
Suggestions welcome on a better name. I was thinking of adding `additional_build_file_contents` to mirror Bazel's `build_file`/`build_file_contents`, but that seems too much.
Fixes #58.
> Allow customizing generated BUILD files

- .travis.yml
Travis is failing with the following error:
ERROR:
/home/travis/.cache/bazel/_bazel_travis/9838a0d5b93391760180ad93f9f7ea99/external/io_bazel_rules_rust/rust/repositories.bzl:3:1:
file '@bazel_tools//tools/build_defs/repo:utils.bzl' does not contain
symbol 'maybe'
Source:
https://travis-ci.org/github/google/cargo-raze/builds/686275069
The maybe symbol was added to "//tools/build_defs/repo"
in June, 2019. However, the version of Bazel used within Travis
is fairly old (0.17.1); this change moves it to the most recent
revision of Bazel.
> Update version of bazel used by Travis CI (0.17.1 -> 3.1.0)

- impl/src/settings.rs
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
- smoke-test.sh
- smoke_test/remote/complicated_cargo_library/cargo/Cargo.toml
- smoke_test/vendored/complicated_cargo_library/cargo/Cargo.toml
Recently, the [`rustc_env` attribute was added to `rules_rust`](https://github.com/bazelbuild/rules_rust/pull/314). This allows making arbitrary environment variables available to `rustc` during compilation, such as the [`PROTOC` variable in `prost-build`](https://github.com/danburkert/prost/blob/2de785aca480779ab0d4442d4bc91a696e3e6c89/prost-build/src/lib.rs#L689).
This PR adds a corresponding setting to `raze`, which is forwarded to the underlying `rust_library` or `rust_binary` rule:
```toml
[raze.crates.prost-build.'0.5.0']
additional_env = { PROTOC = "/usr/local/bin/protoc" }
```
For backwards compatibility, the attribute is only set on the underlying rule if at least one key is specified.
> Add additional_env setting for rules_rust rustc_env

- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
It looks like a `-` was missing in #161, which added additional_env
support.  This causes a blank line with extra whitespace to show up
relative to 0.3.1, or older.
This adds that back in, which matches the rest of the template file and
resolves the whitespace issue.
> Resolve formatting changes in to rust_binary and rust_library templates

- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/planning.rs
- impl/src/templates/partials/rust_binary.template
- impl/src/templates/partials/rust_library.template
- impl/src/util.rs
This PR fixes #143 by checking for renamed packages while exploring dependencies. If a package has been renamed, it will be added to the `aliases` parameter in the generated build rule.
I am still fairly new to Rust programming and it's best practices, so please feel free to nit my implementation.
Once you approve of the implementation, I can write unit tests before merging.
> Fix: Alias renamed dependencies in generated build rules.

- impl/src/planning.rs
- impl/src/settings.rs
I want to be able to optimistically default to generating build scripts by default.
> Add workspace-wide default for gen_buildrs

- impl/Cargo.lock
- impl/Cargo.toml
- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/license.rs
- impl/src/planning.rs
- impl/src/templates/crate.BUILD.template
This PR changes how cargo-raze identifies crate licenses. Currently, proper SPDX syntax is not properly recognized, so a crate with a license "MIT OR Apache-2.0" will be marked as restricted. While one solution would be to split the license string at "OR", I believe this implementation is much more robust, as it will support "AND" if that ever shows up in a crate license.
Using the SPDX crate, a crate's license string is parsed as an SPDX expression. The parser will verify that the licenses and syntax of the expression are valid. If a parse error is returned, the license is marked as restricted and a message is displayed next to the license in the build file. If multiple licenses are allowed ("OR"), the more permissive license is used. If multiple licenses are required ("AND"), the less …
> Fix: Make crate license identification more robust

- impl/src/planning.rs
System crates build scripts may produce environment variables
that may be used by their direct dependencies build script.
For example openssl-sys generates DEP_OPENSSL_VERSION variable
that is then used by openssl crate build scripts.
> Add build script dependencies on sys crates build scripts.

- impl/src/bazel.rs
- impl/src/bin/cargo-raze.rs
Also fix:
* remote folder created on dry run
* remote/BUILD folder does not use prefix path parameter
> Add --output param specifying output folder for generated files.

- impl/src/templates/partials/build_script.template
- impl/src/templates/partials/common_attrs.template
- impl/src/templates/partials/rust_library.template
- impl/src/templates/workspace.BUILD.template
The tags can be used to exclude cargo-raze generated rules from, e.g.
"//...:all" targets. It is useful to prevent Bazel from building
unsupported targets in multiplatform configurations.
> Tag all cargo-raze rules with "cargo-raze" tag.

- impl/src/settings.rs
- impl/src/templates/partials/build_script.template
- smoke-test.sh
Since the switch to the cargo_build_script rule, the
buildrs_additional_environment_variables was no longer working, this
change add this support back.
Fixes #179
> Support additional enviroment variable for build script

- impl/src/templates/remote_crates.bzl.template
I stubbed out a project that I was going to use `cargo-raze` with and noticed that because I did not define any dependencies in my `Cargo.toml` file, `cargo-raze` did not generate valid starlark in the resulting `crates.bzl`. I'm not sure what I should do in the way of updating any tests for this within the repo. But I've added a small repro case in this pull request that fixes the issue.
[test.zip](https://github.com/google/cargo-raze/files/5104185/test.zip)
```
├── BUILD.bazel
├── Cargo.lock
├── Cargo.toml
├── WORKSPACE
├── crates.bzl
├── lib
│   ├── BUILD
│   ├── hello-time.cc
│   └── hello-time.h
├── main
│   ├── BUILD
│   ├── hello-greet.cc
│   ├── hello-greet.h
│   └── hello-world.cc
└── remote
└── BUILD.bazel
3 directories, 13 files
```
Note: The C++ files in the test are copied …
> Fixed issue generating valid Starlark files when no dependencies are defined

- smoke-test.sh
The `./smoke-test.sh` script has been updated to build `cargo-raze` before nuking the examples directory so should a build error occur, you no longer have a huge diff to look at.
> Optimized smoke test script

- impl/src/bazel.rs
This fixes some annoyingly vague errors:
```output
Error: Raze failed to render with cause: "Failed to render 'templates/remote_crates.bzl.template'
```
becomes
```output
Error: Raze failed to render with cause: "Failed to render 'templates/remote_crates.bzl.template'
└─Template 'templates/partials/remote_crates_patch.template' not found"
```
> Improved tera errors

- impl/src/bazel.rs
- impl/src/context.rs
- impl/src/planning.rs
- impl/src/settings.rs
- impl/src/templates/remote_crates.bzl.template
This change allows for users to change the registry url used in the output Bazel files. The new setting:
```toml
[raze]
registry = "https://crates-io.s3-us-west-1.amazonaws.com/crates/{crate}/{crate}-{version}.crate"
```
Is a templated string that will replace `{crate}` with the name of the crate and `{version}` with the version of the crate. This change should not impact any existing files generated from `v5.0.0` of `cargo-raze`
> Added support for custom registry urls

- impl/src/bazel.rs
- impl/src/planning.rs
- impl/src/settings.rs
The use of `&String` in function parameters is discouraged in favor of
`&str` as it otherwise forces passing heap-allocated values (which
doesn't include e.g. string literals).
A small contribution before other, more meaningful ones hopefully :-)
> Change &String function parameters to &str

- impl/src/bazel.rs
- impl/src/bin/cargo-raze.rs
- impl/src/rendering.rs
This replaces the use of strings with `Path` in a few places for better cross platform compatibility.
> Replaced strings with Path objects

- examples/remote/complicated_cargo_library/cargo/remote/winapi-0.3.9.BUILD.bazel
- examples/vendored/complicated_cargo_library/cargo/vendor/winapi-0.3.9/BUILD.bazel
- impl/src/bazel.rs
Before this change, the get_matching_bazel_triples would only allow matching cfg(...) targets. It seems that the intended behaviour was to allow passing triples (such as `x86_64-unknown-linux-gnu`) directly, as per the `format!("cfg(target = \"{}\")", target)` replacement at the beginning of the function. Unfortunately, the match was missing the right case below (`Predicate::Target(tp)` only matches builtin `target_{arch,os,...}`).
This makes this function more consistent with `is_bazel_supported_platform` above, and it seems to solve a bug where target specific dependencies specified with triples (such as is the case for the `winapi` crate in one of the `complicated_cargo_library` example) would be ignored.
FYI you can see the winapi targeted dependencies here: …
> Allow matching triples directly

- impl/src/metadata.rs
- impl/src/planning.rs
There's currently no reason for `fetch_metadata` to require `mut`. Cleaning this up
> fetch_metadata does not need '&mut self'

- examples/remote/complicated_cargo_library/cargo/crates.bzl
- examples/remote/non_cratesio/cargo/crates.bzl
- examples/remote/regression_test/cargo/crates.bzl
- impl/src/settings.rs
- tools/Cargo.lock
This change is broken out of #227 and is necessary to be compatible with https://github.com/ehuss/cargo-clone-crate
> Update registry url

- impl/src/bin/cargo-raze.rs
- impl/src/context.rs
- impl/src/settings.rs
This resolved the following issues flagged by rust-analyzer:
That said though, there should be no behavioral difference in the code.
> Fixed rust-analyzer errors

- impl/src/context.rs
- impl/src/planning.rs
This allows us to generate a strip_prefix directive in the
new_git_repository call.
> Record path to crate root for git deps

- impl/src/templates/partials/build_script.template
Prior to #212 being merged, the following in Cargo.toml was included the resulting BUILD file:
```
[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = { version = "0.2", optional = true }
```
This patch makes it work again, gated with a platform check, eg:
```
cargo_build_script(
name = "libsqlite3_sys_build_script",
srcs = glob(["**/*.rs"]),
crate_root = "build.rs",
edition = "2018",
deps = [
"@raze__cc__1_0_61//:cc",
"@raze__pkg_config__0_3_18//:pkg_config",
] + selects.with_or({
(
"@io_bazel_rules_rust//rust/platform:i686-pc-windows-msvc",
"@io_bazel_rules_rust//rust/platform:x86_64-pc-windows-msvc",
): [
"@raze__vcpkg__0_2_10//:vcpkg",
],
"//conditions:default": [],
}),
```
> build script was missing platform-specific deps

- impl/src/bazel.rs
- impl/src/bin/cargo-raze.rs
- impl/src/planning.rs
- impl/src/util.rs
This is the first commit of work I'm doing in https://github.com/UebelAndre/cargo-raze/tree/sorting 
The goal of that branch is to rearrange parts of the code to be in better alignment with the originally intended code layout.
It seems as though `bazel.rs` is intended to contain rendering logic so the utility functions used for planning should not go in here. This PR moves them into `util.rs`.
> Move util functions out of `bazel` and into `util`

- README.md
- examples/remote/non_cratesio/README.md
- examples/vendored/complicated_cargo_library/README.md
- examples/vendored/hello_cargo_library/README.md
- examples/vendored/non_cratesio_library/README.md
- examples/vendored/regression_test/README.md
- smoke_test/remote/non_cratesio/README.md
- smoke_test/vendored/complicated_cargo_library/README.md
- smoke_test/vendored/hello_cargo_library/README.md
- smoke_test/vendored/non_cratesio_library/README.md
- smoke_test/vendored/regression_test/README.md
`cargo vendor` currently outputs helptext regarding updating
`.cargo/config.toml` in order to replace crates.io sources with the
vendored sources, e.g.:
```
➜ cargo vendor --versioned-dirs
To use vendored sources, add this to your .cargo/config for this
project:
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "path/to/vendor"
```
If a user adds this to their `.cargo/config.toml` configuration prior to
the first run of `cargo vendor`, then `cargo generate-lockfile` and
`cargo vendor --locked` will fail to update the lockfile.
This patch removes the instructions related to generating the lockfile
with `cargo generate-lockfile` (and the subsequent `--locked` flag to
`cargo vendor`), instead preferring to let `cargo vendor` manage the
lockfile. The …
> docs: update instructions for lockfile generation

- examples/WORKSPACE
- examples/remote/binary_dependencies/cargo/remote/ansi_term-0.11.0.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/atty-0.2.14.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/backtrace-0.3.50.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/clicolors-control-1.0.1.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/console-0.9.2.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/texture-synthesis-0.8.0.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/texture-synthesis-cli-0.8.0.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/winapi-0.3.8.BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/winapi-0.3.9.BUILD.bazel
- examples/remote/complicated_cargo_library/cargo/remote/libloading-0.5.2.BUILD.bazel
- examples/remote/complicated_cargo_library/cargo/remote/time-0.1.44.BUILD.bazel
- examples/remote/complicated_cargo_library/cargo/remote/winapi-0.3.9.BUILD.bazel
- examples/vendored/complicated_cargo_library/cargo/vendor/time-0.1.44/BUILD.bazel
- examples/vendored/complicated_cargo_library/cargo/vendor/winapi-0.3.9/BUILD.bazel
- impl/src/util.rs
- smoke-test.sh
gnu has been removed in favour of MSVC in rules_rust, so cargo-raze will need to be updated to match:
https://github.com/bazelbuild/rules_rust/commit/dfce1232e0286623732871802964f76ac2b12098
> support MSVC targets

- impl/src/bin/cargo-raze.rs
The output for things like
```output
Loaded override settings: RazeSettings {
workspace_path: "//remote/non_cratesio/cargo",
incompatible_relative_workspace_path: true,
target: Some(
"x86_64-unknown-linux-gnu",
),
targets: None,
binary_deps: {},
crates: {
"log": {
Version {
major: 0,
minor: 4,
patch: 11,
pre: [],
build: [],
}: CrateSettings {
additional_deps: [],
skipped_deps: [],
extra_aliased_targets: [],
additional_flags: [
"--cfg=atomic_cas",
],
additional_env: {},
gen_buildrs: None,
data_attr: None,
buildrs_additional_environment_variables: {},
patch_args: [],
patch_cmds: [],
patch_cmds_win: [],
patch_tool: None,
patches: [],
additional_build_file: None,
},
},
},
gen_workspace_prefix: "remote_non_cratesio",
genmode: Remote,
output_buildfile_suffix: "BUILD.bazel",
default_gen_buildrs: …
```
> Gated loud output behind the `--verbose` flag.

- impl/src/planning/subplanners.rs
`Vendored` genmode relies on the behavior of `cargo vendor` and shouldn't do anything special for "binary dependencies".
> Checksums for binary dependencies shouldn't be fetched in genmode=vendored

- impl/src/bin/cargo-raze.rs
The numeric flags didn't appear to be working. Verbose is now a boolean
```command
no_deps % /Users/user/Code/cargo-raze/impl/target/debug/cargo-raze raze -v
```
```output
Loaded override settings: RazeSettings {
workspace_path: "//remote/no_deps/cargo",
incompatible_relative_workspace_path: true,
target: None,
targets: None,
binary_deps: {},
crates: {},
gen_workspace_prefix: "remote_no_deps",
genmode: Remote,
output_buildfile_suffix: "BUILD.bazel",
default_gen_buildrs: false,
registry: "https://crates.io/api/v1/crates/{crate}/{version}/download",
index_url: "https://github.com/rust-lang/crates.io-index",
}
Generated /Users/user/Code/cargo-raze/examples/remote/no_deps/cargo/remote/BUILD.bazel successfully
Generated /Users/user/Code/cargo-raze/examples/remote/no_deps/cargo/BUILD.bazel …
```
> Fixed verbose output

- examples/remote/binary_dependencies/cargo/BUILD.bazel
- examples/remote/binary_dependencies/cargo/crates.bzl
- examples/remote/complicated_cargo_library/cargo/BUILD.bazel
- examples/remote/complicated_cargo_library/cargo/crates.bzl
- examples/remote/no_deps/cargo/BUILD.bazel
- examples/remote/no_deps/cargo/crates.bzl
- examples/remote/non_cratesio/cargo/BUILD.bazel
- examples/remote/non_cratesio/cargo/crates.bzl
- examples/vendored/complicated_cargo_library/cargo/BUILD.bazel
- examples/vendored/hello_cargo_library/cargo/BUILD.bazel
- examples/vendored/non_cratesio_library/cargo/BUILD.bazel
- impl/src/rendering/bazel.rs
- impl/src/rendering/templates/partials/header.template
- impl/src/rendering/templates/remote_crates.bzl.template
- impl/src/rendering/templates/workspace.BUILD.template
Since there is a nearly identical header for two types of files, I thought it'd make sense to create a single source of truth for this.
This is more work that's been broken out of https://github.com/google/cargo-raze/pull/276
> Moved template header into it's own file

- README.md
- examples/remote/README.md
- examples/remote/binary_dependencies/Cargo.toml
- examples/remote/complicated_cargo_library/Cargo.toml
- examples/remote/no_deps/Cargo.toml
- examples/remote/non_cratesio/Cargo.toml
- examples/remote/non_cratesio/README.md
- examples/vendored/complicated_cargo_library/Cargo.toml
- examples/vendored/hello_cargo_library/Cargo.toml
- examples/vendored/non_cratesio_library/Cargo.toml
- impl/src/settings.rs
- smoke_test/remote/README.md
- smoke_test/remote/binary_dependencies/Cargo.toml
- smoke_test/remote/complicated_cargo_library/Cargo.toml
- smoke_test/remote/no_deps/Cargo.toml
- smoke_test/remote/non_cratesio/Cargo.toml
- smoke_test/remote/non_cratesio/README.md
- smoke_test/vendored/complicated_cargo_library/Cargo.toml
- smoke_test/vendored/hello_cargo_library/Cargo.toml
- smoke_test/vendored/non_cratesio_library/Cargo.toml
Cargo sets aside the [`[package.metadata]`][md] namespace for use by
third-party tools like `cargo-raze`. By specifying configuration under
`[package.metadata.raze]` rather than `[raze]`, we avoid an “unused
manifest key: raze” warning on every Cargo command.
This patch teaches `cargo-raze` to accept either `[raze]` or the new
`[package.metadata.raze]`. In case of conflict, it prints a warning and
uses the value of `[package.metadata.raze]`. In the future, we can
remove the `[raze]` key entirely if desired.
Fixes #273.
Changes outside of `impl/` generated by:
```
git ls-files -z ':!impl' | xargs -0 sed -i 's/\[raze/[package.metadata.raze/'
```
[md]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table
Test Plan:
With this patch, running `./smoke-test.sh` passes both …
> Accept `[package.metadata.raze]`, superseding `[raze]`

- impl/Cargo.toml
- impl/src/context.rs
- impl/src/planning.rs
- impl/src/planning/checks.rs
- impl/src/planning/subplanners.rs
- impl/src/rendering/bazel.rs
- impl/src/settings.rs
This is a little WIP, as we / I need to add unit and integration tests for this.
In reworking #123 a little, to allow for aliases to be presented in the "root" raze crate and to avoid a problem with crates presenting multiple versions of aliases I added in _basic_ support for using the semver library to do matches for alias determination.
It occured to me, that rather than _just_ use semver in that one specific place we should expose the richness of the semver objects into raze more generally. As such this commit exposes semver to raze and allows it to use semver for both version details and in matching configuration settings.
Raze settings come in the form of a [TOML] section like so
```toml
[raze.crates.some-crate.'1.2.3']
some_new_setting = true
```
Where the version number (in the …
> Semver matching

- impl/src/bin/cargo-raze.rs
This patch adds a `--version` flag that causes `cargo-raze` to print
version info and exit. The functionality is built into Docopt, so it’s
just a matter of hooking it up to the `CARGO_PKG_VERSION` env var.
Test Plan:
When invoking the binary to test, make sure to pass an extra `raze` arg
so that docopt matches the `cargo raze` (not `cargo-raze`) pattern:
```
cargo run -- raze --version  # or...
cargo install --path . && cargo raze --version
```
Either invocation prints “cargo-raze 0.7.0” and a newline before exiting
successfully. This format is consistent with the `--version` behavior of
`cargo` and `rustc` themselves.
wchargin-branch: cli-version
> cli: implement `--version`

- examples/remote/binary_dependencies/cargo/remote/BUILD.bitflags-1.2.1.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.byteorder-1.3.4.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.crc32fast-1.2.0.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.libc-0.2.67.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.libc-0.2.77.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.miniz_oxide-0.4.2.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.num-integer-0.1.42.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.num-iter-0.1.40.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.num-rational-0.2.3.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.num-traits-0.2.11.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.proc-macro-error-0.4.9.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.proc-macro2-1.0.9.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.rustversion-1.0.2.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.syn-1.0.16.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.winapi-0.3.8.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.winapi-0.3.9.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.winapi-i686-pc-windows-gnu-0.4.0.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.winapi-x86_64-pc-windows-gnu-0.4.0.bazel
- examples/remote/complicated_cargo_library/cargo/remote/BUILD.syn-0.15.44.bazel
- impl/src/rendering/templates/crate.BUILD.template
This fixes a regression where a newline had been removed from outputs resulting in lines like
```python
```
This corrects that so the same template renders correctly:
```python
```
> Fixed regression in rendered templates

- impl/src/context.rs
- impl/src/planning/subplanners.rs
- impl/src/rendering/bazel.rs
The links attribute is needed to infer the name of environment variables to pass to sys crate dependencies.
Fixes #288
> Add links to CargoContext

- impl/src/planning/subplanners.rs
- impl/src/settings.rs
- impl/src/util.rs
A new setting `rust_rules_workspace_name` has been added which allows users to specify the name of the `rules_rust` repository they wish to generate files with.
This is blocked by https://github.com/google/cargo-raze/pull/296
This blocks https://github.com/bazelbuild/rules_rust/pull/500
> Added setting `rust_rules_workspace_name`

- impl/Cargo.lock
- impl/Cargo.toml
This pulls in https://github.com/ehuss/cargo-clone-crate/pull/3 which removes some unnecessary transitive dependencies.
> Updated dependencies

- examples/remote/complicated_cargo_library/Cargo.toml
- examples/remote/no_deps/Cargo.toml
- examples/remote/non_cratesio/Cargo.toml
- examples/remote/non_cratesio/cargo/remote/BUILD.atty-0.2.14.bazel
- examples/remote/non_cratesio/cargo/remote/BUILD.termcolor-0.3.6.bazel
- examples/vendored/complicated_cargo_library/Cargo.toml
- examples/vendored/hello_cargo_library/Cargo.toml
- examples/vendored/non_cratesio_library/Cargo.toml
- examples/vendored/non_cratesio_library/cargo/vendor/atty-0.2.14/BUILD.bazel
- examples/vendored/non_cratesio_library/cargo/vendor/iovec-0.1.4/BUILD.bazel
- examples/vendored/non_cratesio_library/cargo/vendor/termcolor-0.3.6/BUILD.bazel
- impl/src/settings.rs
- smoke_test/remote/complicated_cargo_library/Cargo.toml
- smoke_test/remote/no_deps/Cargo.toml
- smoke_test/remote/non_cratesio/Cargo.toml
- smoke_test/vendored/complicated_cargo_library/Cargo.toml
- smoke_test/vendored/hello_cargo_library/Cargo.toml
- smoke_test/vendored/non_cratesio_library/Cargo.toml
This flags certain settings as deprecated. Namely:
- `incompatible_relative_workspace_path` is planned to be removed
- `target` can be replaced by `targets`
- `default_gen_buildrs` is expected to change it's default settings per https://github.com/bazelbuild/rules_rust/issues/490
Blocked by https://github.com/google/cargo-raze/pull/302
> Added deprecation warnings

- CODEOWNERS
Based on the discussion https://github.com/google/cargo-raze/discussions/314 It makes sense to me to have @acmcarther be the only code owner represented for the repo.
> Cleaning up code owners file

- impl/src/checks.rs
- impl/src/planning.rs
- impl/src/testing.rs
- impl/src/testing/metadata_templates/dummy_modified_metadata.json.template
This is a spinoff of https://github.com/google/cargo-raze/pull/319#discussion_r543835396 where I needed to update tests using the `dummy_injecting_metadata` and opted to replace that function with a templated dump of the metadata it's generating to cleanup how many ways metadata is created for tests. Ultimately, I think this metadata can be deleted since it's quite similar to one of the pacakges included in `dummy_workspace_members_metadata.json.template`. This PR should also be looked at when actioning #310
> Removed `dummy_injecting_metadata` in favor of a templated metadata dump

- impl/src/settings.rs
It turns out the functionality was already removed so this is just cleanup. Sorry about that 😞
> Removed `incompatible_relative_workspace_path`

- impl/src/settings.rs
This causes raze to generate an error when unexpected fields are in the `[*.metadata.raze]` section of a `Cargo.toml`
With the following diff:
```diff
diff --git a/examples/remote/cargo_workspace/Cargo.toml b/examples/remote/cargo_workspace/Cargo.toml
index 097d943c..047f39c7 100644
--- a/examples/remote/cargo_workspace/Cargo.toml
+++ b/examples/remote/cargo_workspace/Cargo.toml
@@ -11,3 +11,4 @@ gen_workspace_prefix = "remote_cargo_workspace"
genmode = "Remote"
default_gen_buildrs = true
package_aliases_dir = "cargo"
+oops = "yup"
\ No newline at end of file
```
The following error is generated when running `cargo raze --manifest-path=./examples/cargo_workspace/Cargo.toml` 
```output
Error: Raze failed with cause: "unknown field `oops`, expected one of `workspace_path`, …
```
> Unknown fields will now cause failures

- impl/src/settings.rs
Closes https://github.com/bazelbuild/rules_rust/issues/490
In the common case, running `build.rs` is fine and doesn't break determinism or violate any sandboxing. For the cases that do, users can set `gen_buildrs = false` in the `CrateSetting` of the crate that has a complex `build.rs` file to avoid undesirable behavior. There are enough settings to work around most cases users would run into.
> `default_gen_buildrs` now defaults to `true`

- impl/src/bin/cargo-raze.rs
- impl/src/planning.rs
- impl/src/settings.rs
This allows `cargo raze` to be run anywhere within a cargo workspace. This means when iterating on a target, one can simply call `cargo raze && bazel build //my:target` from anywhere within a cargo workspace to generate new BUILD files and have them immediately used in the next run of Bazel.
To accomplish this, a restructuring was done to the `cargo-raze.rs` file. An overview of what the binary is doing can more easily be seen in the `main` function where the logic that was all once in that single function has been split into smaller functions to group the steps `cargo-raze` does to generate BUILD files.
`settings::load_settings_from_workspace` was add to be able to fetch metadata from an arbitrary location in a cargo workspace. This will use the new `SettingsMetadataFetcher` struct to …
> Cargo raze can now be run from anywhere within a cargo workspace

- impl/src/bin/cargo-raze.rs
- impl/src/rendering.rs
- impl/src/rendering/bazel.rs
- impl/src/rendering/templates/crate.BUILD.template
- impl/src/rendering/templates/partials/build_script.template
In working on https://github.com/bazelbuild/rules_rust/pull/500 I realized that not all the uses of the `rules_rust` workspace name were being templetized. This PR fixes this such that the `load` statements also use `rust_rules_workspace_name`. (Sorry about missing this).
> Fixed missing use of `rust_rules_workspace_name` setting in templates

- impl/src/bin/cargo-raze.rs
This fixes a breakage between two commits merged earlier.
> Fixed compile error

- examples/remote/cargo_workspace/num_printer/cargo/BUILD.bazel
- examples/remote/cargo_workspace/printer/cargo/BUILD.bazel
- examples/remote/cargo_workspace/rng/cargo/BUILD.bazel
- examples/vendored/cargo_workspace/cargo/BUILD.bazel
- examples/vendored/cargo_workspace/num_printer/cargo/BUILD.bazel
- examples/vendored/cargo_workspace/printer/cargo/BUILD.bazel
- examples/vendored/cargo_workspace/rng/cargo/BUILD.bazel
- examples/vendored/complicated_cargo_library/cargo/BUILD.bazel
- examples/vendored/hello_cargo_library/cargo/BUILD.bazel
- examples/vendored/non_cratesio_library/cargo/BUILD.bazel
- impl/src/rendering/bazel.rs
This would only impact projects using cargo workspace functionality since they're the the only projects that would have multiple workspace members. 
Aliases are rendered for each workspace member in the Bazel package where they're located, but only the root package will have a `crates.bzl` file. This PR limits where the `exports_files` macro is declared to the correct places.
> Fixed a bug where export_files was being rendered into BUILD files it shouldn't have been

- impl/src/bin/cargo-raze.rs
- impl/src/checks.rs
- impl/src/context.rs
- impl/src/error.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/planning/crate_catalog.rs
- impl/src/planning/license.rs
- impl/src/planning/subplanners.rs
- impl/src/rendering.rs
- impl/src/settings.rs
- impl/src/testing.rs
- impl/src/util.rs
Closes https://github.com/google/cargo-raze/issues/299
This changes the documentation style of 
```rust
/** Header
*
* body
*/
fn hello() {}
```
to 
```rust
/// Header
///
/// body
fn hello() {}
```
So that documentation can be generated via rustdoc
> Changed comment block style to be compatible with rustdoc

- README.md
- impl/src/settings.rs
Per [issue 335], I didn't find these docstrings very helpful. The
important bit of this property appears to be "this is where outputs go".
Try to make that clearer in the property docstring and the README.
Also do a little cleanup:
- README:
- Deduplicate the `Cargo.toml` contents between two headers. We only need to list the specifics once.
- Use `package.metadata.raze` when used in a package-metadata context (rather than workspace-metadata)
- Fix typos 
- Run `rustfmt` on `settings.rs` (my precommits complain otherwise).
[issue 335]: https://github.com/google/cargo-raze/issues/335
> Update comments on workspace_path

- impl/src/settings.rs
This is the safer option. As sated by the previous warning. Users can set this to `"."` to prevent any change in behavior from previous versions of `cargo-raze`.
> `package_aliases_dir` now defaults to `cargo`

- impl/src/bin/cargo-raze.rs
- impl/src/checks.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/settings.rs
- impl/src/testing.rs
- impl/src/util.rs
This PR adds a new argument `--generate-lockfile` which will force a new lockfile to be generated.
`Cargo.toml` and `Cargo.lock` were basically never used for anything other than finding the cargo workspace. It's simpler to pass around a `Path` and allow the underlying cargo command to handle finding the correct metadata.
This will always generate a `Cargo.raze.lock` file which will take precedence over an existing `Cargo.lock` file. As a reminder, this file exists because to allow projects using `binary_deps` to have a lockfile that doesn't conflict with the standard lockfile. I'm hoping to one day delete the need for this file and standardize on the canonical `Cargo.lock` file, but for now, the use of `Cargo.raze.lock` makes the outputs of `cargo-raze` more consistent.
Running this …
> Added `--generate-lockfile` for generating a new lockfile

- impl/src/metadata.rs
- impl/src/settings.rs
Similar to [cargo_metadata::MetadataCommand::cargo_path](https://docs.rs/cargo_metadata/0.12.3/cargo_metadata/struct.MetadataCommand.html#method.cargo_path) (which is the underlying crate used for the primary cargo commands in `cargo-raze`), Cargo raze will now accept an optional `CARGO` environment variable for specifying the path to the Cargo binary. This makes it realistic to use `cargo-raze` in Bazel rules since `cargo-raze` requires a Cargo binary.
> Added support for a `CARGO` environment variable

- examples/remote/binary_dependencies/cargo/remote/BUILD.ferris-says-0.2.0.bazel
- examples/remote/cargo_workspace/cargo/remote/BUILD.ferris-says-0.2.0.bazel
- examples/remote/complicated_cargo_library/cargo/remote/BUILD.aho-corasick-0.6.10.bazel
- examples/remote/complicated_cargo_library/cargo/remote/BUILD.cc-1.0.60.bazel
- examples/remote/complicated_cargo_library/cargo/remote/BUILD.crossbeam-0.3.2.bazel
- examples/remote/complicated_cargo_library/cargo/remote/BUILD.regex-0.2.5.bazel
- examples/remote/non_cratesio/cargo/remote/BUILD.aho-corasick-0.6.10.bazel
- examples/vendored/cargo_workspace/cargo/vendor/ferris-says-0.2.0/BUILD.bazel
- examples/vendored/cargo_workspace/cargo/vendor/getrandom-0.1.15/BUILD.bazel
- examples/vendored/cargo_workspace/cargo/vendor/miniz_oxide-0.4.3/BUILD.bazel
- examples/vendored/complicated_cargo_library/cargo/vendor/aho-corasick-0.6.10/BUILD.bazel
- examples/vendored/complicated_cargo_library/cargo/vendor/crossbeam-0.3.2/BUILD.bazel
- examples/vendored/non_cratesio_library/cargo/vendor/aho-corasick-0.6.10/BUILD.bazel
- impl/src/rendering/bazel.rs
- impl/src/rendering/templates/partials/rust_binary.template
- impl/src/rendering/templates/partials/rust_library.template
This is a slight improvement to how dependencies for `rust_binary` and `rust_library` targets get rendered. Instead of looping over multiple lists and rendering labels for dependencies, they're combined into a single list, sorted and then rendered. 
Unfortunately, this does not mean that the `buildifier: leave-alone` tag can be removed. Buildifier appears to follow a different sorting rule than what [tera](https://github.com/Keats/tera) makes available. To solve for this, we should register a custom [filter](https://tera.netlify.app/docs#filters) that performs a Buildifier compliant sort.
A diff can be found below highlighting the differences: 
```diff
diff --git a/examples/vendored/cargo_workspace/cargo/vendor/ferris-says-0.2.0/BUILD.bazel …
```
> Rust library and binary dependencies are all sorted before rendering

- impl/src/bin/cargo-raze.rs
Currently, argument parsing is broken for `cargo-raze` when using the tool as a cargo subcommand
```command
cargo-raze % cargo raze --manifest-path ./examples/vendored/hello_cargo_library/Cargo.toml && echo $?
```
```output
Invalid arguments.
Usage:
cargo raze (-h | --help)
cargo raze [--verbose] [--quiet] [--color=<WHEN>] [--dryrun] [--cargo-bin-path=<PATH>]
[--manifest-path=<PATH>] [--output=<PATH>] [--generate-lockfile]
cargo raze (-V | --version)
```
The changes in this PR fix the issue.
```command
cargo-raze % cargo raze --manifest-path ./examples/vendored/hello_cargo_library/Cargo.toml && echo $?
```
```output
0
```
The changes here also ensure argument parsing continues to work when passed directly to the binary. This is evident by the passing build in CI since `smoke-test.sh` …
> Strip cargo subcommand string from arguments to fix arg parsing

- .bazelci/presubmit.yml
This PR adds an initial .bazelci/presubmit.yml per onboarding instructions of github.com/bazelbuild/continuous-integration.
We won't be able to sanity check this because we haven't actually been onboarded yet (although a CI run _might_ trigger because I created a pipeline already).
> Add initial bazelci/presubmit.yml

- .github/workflows/ci.yaml
- impl/src/bin/cargo-raze.rs
- impl/src/planning.rs
- impl/src/testing.rs
I don't have a lot of familiarity with bazelci, so I'm not sure how much I can help on that front.  My team uses github actions so I'm a little more familiar with that.
This PR puts together a basic version of a cargo-only version of the CI.  It's based off of the [MRSV example](https://github.com/actions-rs/meta/blob/master/recipes/msrv.md) from the actions-rs project.  I might have a chance to look at bazel-based builds later on, but perhaps this will unblock some things.
Perhaps there was something I didn't completely understand on the rustfmt options, but it seems like there were some formatting regressions that I fixed in a separate commit in the stack.
> Add github actions for cargo-based builds

- .github/workflows/ci.yaml
- impl/src/bin/cargo-raze.rs
- impl/src/checks.rs
- impl/src/metadata.rs
- impl/src/planning/license.rs
- impl/src/planning/subplanners.rs
- impl/src/rendering/bazel.rs
- impl/src/settings.rs
- impl/src/util.rs
Most of these are efficiency clean-ups, by replacing modifications with
_else, so that error path is evaluated lazily.  Clippy is somewhat
opinionated, so this does end up adjusting some conventions.  However,
on the whole, blindly accepting it as a linter is probably a win for the
project.
> Fix clippy lints and enable clippy in CI.

- impl/src/metadata.rs
- impl/src/settings.rs
- impl/src/util.rs
A bug was fixed where the `"CARGO"` environment variable wasn't being when looking for a cargo binary. This has been corrected and is now in use.
> Fixed missing "CARGO" environment variable uses

- README.md
- WORKSPACE.bazel
- examples/WORKSPACE
- impl/BUILD.bazel
Using the changes introduced in https://github.com/bazelbuild/rules_rust/pull/588, cargo raze can now correctly specify the `cargo` and `rustc` binaries to use during tests and no longer require the host to have either installed. For users running the target, however, the binaries are still required to be installed but this should be a simple change that can be made in the future
> Set `CARGO` and `RUSTC` environment variables to make Bazel tests more hermetic

- impl/src/settings.rs
Also add a test that ensures the error is reported and a panic doesn't
occur.
> Fix panic when invoked on crate missing metadata (#377)

- .bazelci/presubmit.yml
- README.md
Windows is broken for a somewhat inconsequential reason:
TL;DR: It can't execute the repository rule for `cargo_raze_examples`. I think this can be skipped in windows if necessary.
```
$ bazel --output_user_root=C:/b --nomaster_bazelrc --bazelrc=/dev/null info
--
  | INFO: SHA256 (https://static.rust-lang.org/dist/cargo-1.49.0-x86_64-pc-windows-msvc.tar.gz) = 84b44835a3f275fef70cd86a527d086c537e59fb3209fe8bbef1eeb1da6edbb6
  | INFO: Repository cargo_raze_examples instantiated at:
  | C:/b/bk-windows-r4v8/bazel/cargo-raze/WORKSPACE.bazel:32:20: in <toplevel>
  | C:/b/bk-windows-r4v8/bazel/cargo-raze/tools/examples_repository.bzl:108:25: in examples_repository
  | Repository rule _examples_repository defined at:
  | C:/b/bk-windows-r4v8/bazel/cargo-raze/tools/examples_repository.bzl:82:39: …
```
> Disable windows build in Buildkite, and update badge

- tools/BUILD.bazel
- tools/examples_repository.bzl
- tools/examples_repository_tools.bat
This fixes vendoring examples source on windows machines. I found out that just because `bash` exists on a Windows host (namely on a BuildKite Windows worker), doesn't mean the programs are the same. The issue I ran into was `FIND: Parameter format not correct` and this is because the `find` program on a unix host is not the same on windows. Thus the bash script would not have worked as is. I decided to write my first ever batch script.
> Fixed windows bug in examples repository rule

- .bazelci/presubmit.yml
Reverts google/cargo-raze#375
This is broken. Aside from whatever induced the breakage, it's also super spammy in the logs:
https://buildkite.com/organizations/bazel/pipelines/cargo-raze/builds/68/jobs/8c6c14e5-5d97-4e8e-ad07-e159cb8fd185/raw_log
literally MBs of this:
```
Running Cargo Vendor for cargo_workspace
/workdir/examples/vendored/cargo_workspace /workdir/examples/vendored/cargo_workspace ~/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/cargo_raze/bazel-out/k8-fastbuild/bin/tools/examples_check.runfiles/cargo_raze
Running Cargo Vendor for cargo_workspace
/workdir/examples/vendored/cargo_workspace /workdir/examples/vendored/cargo_workspace /workdir/examples/vendored/cargo_workspace ~/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29 …
```
> Revert "Ensure examples are up to date in CI"

- repositories.bzl
- third_party/curl/BUILD.curl.bazel
- third_party/libgit2/BUILD.libgit2.bazel
- third_party/libssh2/BUILD.libssh2.bazel
- third_party/pcre/BUILD.pcre.bazel
There is a MacOS bug fix in the latest `rules_foreign_cc` release that should be included here if users are going to be relying on building `cargo-raze` in Bazel. This also fixes some bugs that're now caught in the newest commit.
> Update to latest `rules_foreign_cc` commit

- impl/src/rendering/bazel.rs
- impl/src/rendering/templates/partials/crates_macro.template
In the way the dependency maps were being rendered, it always assumed the bazel package containing the cargo workspace is not an empty file. This is the case for the `cargo_workspace` examples in this repo but is an incorrect assumption. This PR fixes that.
Closes https://github.com/google/cargo-raze/issues/354
> Fixed leading slashes in experimental API dependencies maps

- BUILD.bazel
- impl/BUILD.bazel
- tools/BUILD.bazel
- tools/wrapper.sh
I forgot that I still have cargo installed on my machine when testing this scenario. The `//:raze` target should be a wrapper script that explicitly sets the needed environment variables for running `cargo-raze` without installing cargo components on the host
With the following diff:
```diff
diff --git a/examples/WORKSPACE b/examples/WORKSPACE
index 327a21ef..bf138d0c 100644
--- a/examples/WORKSPACE
+++ b/examples/WORKSPACE
@@ -19,3 +19,12 @@ rust_repositories()
load("//:repositories.bzl", "repositories")
repositories()
+
+local_repository(
+    name = "cargo_raze",
+    path = "..",
+)
+load("@cargo_raze//:repositories.bzl", "cargo_raze_repositories")
+cargo_raze_repositories()
+load("@cargo_raze//:transitive_deps.bzl", "cargo_raze_transitive_deps")
```
I'm still able to run raze in …
> Fixed the need for cargo on the host when running `//:raze`

- README.md
This PR updates documentation for what users would need to do to be able to add `cargo-raze` to their WORKSPACE file and run it as a tool built purely in Bazel for environments that do not have Cargo installed on the host.
> Added documentation for the Bazel-only workflow

- README.md
> Add note about rules_foreign_cc when using @cargo_raze//:raze.

- README.md
- WORKSPACE.bazel
- repositories.bzl
- transitive_deps.bzl
> Pull @rules_rust in cargo_raze_repositories().

- impl/src/rendering/templates/partials/build_script.template
This was added to rules_rust in
https://github.com/bazelbuild/rules_rust/pull/480 and we started parsing
out the metadata in cargo_raze in #281 but didn't start populating it in
generated BUILD files.
This enables us to remove a hack in rules_rust where we try to infer the
correct value for the `links` attribute if it wasn't set, based on the
name, which in turn will allow us to remove the `crate_name` attribute
completely.
> Set links attribute

- impl/src/metadata.rs
This pr should resolve the issue of the windows path have an extra slash iterating the workspace members.
> Resolve Parsing of workspace members paths broken on Windows

- repositories.bzl
- third_party/curl/BUILD.curl.bazel
- third_party/iconv/BUILD.iconv.bazel
- third_party/libgit2/BUILD.libgit2.bazel
- third_party/libssh2/BUILD.libssh2.bazel
- third_party/openssl/BUILD.openssl.bazel
- third_party/pcre/BUILD.pcre.bazel
- transitive_deps.bzl
[rules_foreign_cc 0.2.0](https://github.com/bazelbuild/rules_foreign_cc/releases/tag/0.2.0) was just cut and contains some API changes. This PR updates the user of `rules_foreign_cc` rules to use the new API.
> Updated rules_foreign_cc to 0.2.0 and migrated rules to new api.

- impl/src/context.rs
- impl/src/metadata.rs
- impl/src/planning.rs
- impl/src/planning/subplanners.rs
- impl/src/rendering/bazel.rs
- impl/src/rendering/templates/partials/build_script.template
- impl/src/rendering/templates/partials/common_attrs.template
- impl/src/rendering/templates/partials/targeted_dependencies.template
- impl/src/rendering/templates/workspace.BUILD.template
- impl/src/settings.rs
- impl/src/testing.rs
- impl/src/util.rs
This addresses @dfreese's comments in #282 and preserves @GregBowyer's commit in the history.
> Rework planning to use resolve tree and not packages (updated)

- impl/src/context.rs
- impl/src/planning.rs
- impl/src/planning/subplanners.rs
- impl/src/testing.rs
- impl/src/testing/metadata_templates/subplan_omits_platform_deps_already_in_default_deps.json.template
I'll add some tests if folks think this is the right approach. It doesn't fix every edge case I'm aware of, but adding coverage for this very common case would help move things forward. It's very easy to hit this bug if you enable a lot of platforms in raze settings. For example, this patch fixes #389 for me.
> Don't allow default deps in planning of platform deps.

- impl/Cargo.lock
- impl/Cargo.toml
- impl/src/context.rs
- impl/src/metadata.rs
- impl/src/planning/subplanners.rs
- impl/src/rendering/bazel.rs
- impl/src/rendering/templates/remote_crates.bzl.template
- third_party/cargo/remote/BUILD.url-2.2.1.bazel
This relies on the registry information being in .cargo/config.toml (and
will proactively error if other keys are found in there).
The reason for this is that we need to run `cargo metadata` before we
even parse out config, and we can't run `cargo metadata` without having
this data active for that `cargo` invocation. It also simplifies
implementation a lot, by just copying around one file rather than
needing to generate config for `cargo` to use.
Fixes #24.
> Support additional registries

- examples/remote/binary_dependencies/BUILD.bazel
- examples/remote/build_dependencies/BUILD.bazel
- examples/remote/cargo_workspace/num_printer/BUILD.bazel
- examples/remote/cargo_workspace/printer/BUILD.bazel
- examples/remote/cargo_workspace/rng/BUILD.bazel
- examples/remote/complicated_cargo_library/BUILD
- examples/remote/dev_dependencies/BUILD.bazel
- examples/remote/no_deps/BUILD
- examples/remote/non_cratesio/BUILD
- examples/vendored/cargo_workspace/num_printer/BUILD.bazel
- examples/vendored/cargo_workspace/printer/BUILD.bazel
- examples/vendored/cargo_workspace/rng/BUILD.bazel
- examples/vendored/complicated_cargo_library/BUILD
- examples/vendored/hello_cargo_library/BUILD
- examples/vendored/non_cratesio_library/BUILD
- impl/BUILD.bazel
- repositories.bzl
- third_party/curl/BUILD.curl.bazel
- third_party/iconv/BUILD.iconv.bazel
- third_party/openssl/BUILD.openssl.bazel
- third_party/pcre/pcre_repositories.bzl
These two repos have breaking changes in latest. This means that importing this repo in a `WORKSPACE` fails if newer versions of rules_rust and/or rules_foreign_cc are already imported.
> Update rules_rust and rules_foreign_cc to latest

- impl/src/rendering/templates/crate.BUILD.template
- impl/src/rendering/templates/partials/common_attrs.template
As `cargo raze` sanitizes target names (replacing `-` with `_` - could you shed some light on why that needs to be done?), it's impossible to retrieve the name of the original crate.
As a solution, we're including the original name of the crate into Bazel target's `tags`.
> Preserve original crate name as a Bazel target tag

- impl/src/metadata.rs
Fix #417.
The parameters for symlink_file for windows were in wrong order.
> Fix symlink for windows.

- examples/remote/binary_dependencies/cargo/BUILD.bazel
- examples/remote/binary_dependencies/cargo/remote/BUILD.bazel
- examples/remote/build_dependencies/cargo/BUILD.bazel
- examples/remote/build_dependencies/cargo/remote/BUILD.bazel
- examples/remote/cargo_workspace/cargo/BUILD.bazel
- examples/remote/cargo_workspace/cargo/remote/BUILD.bazel
- examples/remote/complicated_cargo_library/cargo/BUILD.bazel
- examples/remote/complicated_cargo_library/cargo/remote/BUILD.bazel
- examples/remote/dev_dependencies/cargo/BUILD.bazel
- examples/remote/dev_dependencies/cargo/remote/BUILD.bazel
- examples/remote/no_deps/cargo/BUILD.bazel
- examples/remote/no_deps/cargo/remote/BUILD.bazel
- examples/remote/non_cratesio/cargo/BUILD.bazel
- examples/remote/non_cratesio/cargo/remote/BUILD.bazel
- examples/vendored/cargo_workspace/cargo/BUILD.bazel
- impl/src/rendering/bazel.rs
This allows users to easily include these sources in other targets like those from `rules_pkg` as well as run `buildifier` using the new test rules.
> Added a filegroup for all Bazel sources

- CHANGELOG.md
- CODEOWNERS
Updating codeowners so that reviews on PRs with more eyes.  This also
updates the changelog to the extent I'm willing to back-fill it.  Using
v0.13.0 should probably be considered a baseline.
> Update codeowners and changelog

- impl/src/util.rs
This is required for some dependencies to correctly handle select
statements like non-windows.
Related: https://github.com/bazelbuild/rules_rust/pull/1362
> Add armv7-linux-androideabi tier 2 CPU

- BUILD.bazel
- README.md
- examples/WORKSPACE
- impl/BUILD.bazel
- impl/Cargo.lock
- impl/Cargo.toml
- impl/src/metadata.rs
- impl/src/testing.rs
- repositories.bzl
- third_party/cargo/crates.bzl
- third_party/cargo/remote/BUILD.async-trait-0.1.48.bazel
- third_party/cargo/remote/BUILD.ctor-0.1.22.bazel
- third_party/cargo/remote/BUILD.futures-macro-0.3.13.bazel
- third_party/cargo/remote/BUILD.openssl-macros-0.1.0.bazel
- third_party/cargo/remote/BUILD.pest_generator-2.1.3.bazel
- third_party/cargo/remote/BUILD.pin-project-internal-1.0.6.bazel
- third_party/cargo/remote/BUILD.serde_derive-1.0.126.bazel
- third_party/cargo/remote/BUILD.syn-1.0.80.bazel
- third_party/cargo/remote/BUILD.tokio-macros-1.1.0.bazel
- third_party/cargo/remote/BUILD.tracing-attributes-0.1.15.bazel
- third_party/cargo/remote/BUILD.value-bag-1.0.0-alpha.6.bazel
- third_party/cargo/remote/BUILD.wasm-bindgen-backend-0.2.73.bazel
- third_party/cargo/remote/BUILD.wasm-bindgen-macro-support-0.2.73.bazel
- transitive_deps.bzl
This fixes the path problems in #485.
The `rust_analyzer` rule is no longer needed, but rust_analyzer still works as we have it here. See https://github.com/bazelbuild/rules_rust/pull/1405.
> Update to rules_rust 0.6.0

- tools/examples_repository.bzl
https://github.com/bazelbuild/rules_rust/pull/1289 exposes a better way to figure out the right triple to use with `load_arbitrary_tool`. In particular, we avoid assuming that `x86_64` is always the correct architecture.
> Replace incomplete repository_os logic with get_host_triple

- impl/src/metadata.rs
A couple of string copies can be avoided by using as_ref() instead.
> Fix clippy errors at stable (1.63.0)

- impl/src/features.rs
I made a simple typo (spelled a platform wrong), and figure out what was wrong was next to impossible without this output. With this change, it's obvious what the problem is.
> Print the error message when cargo tree fails

- repositories.bzl
- tools/BUILD.bazel
- transitive_deps.bzl
Bump rules_rust to version 0.11.0 and rules_foreign_cc to 0.9.0
**This MR breaks compatibility with rules_rust < 0.7.0**
Closes #522
Signed-off-by: Alan Diego dos Santos <alandiegosantos@gmail.com>
> Bump rules_rust and rules_foreign_cc

- DEVELOPMENT.md
Looking through the commit history, it looks like forgetting to re-generated some of the outputs that get checked has happened multiple times. Doing this often makes bugs in new changes obvious when things fail to build.
Ideally CI would verify this (there's a TODO for it in presubmit.yml), but as a starting point let's at least document it.
> Document the commands to regenerate checked-in outputs
