src/planning.rs

This fixes https://github.com/acmcarther/cargo-raze/issues/26, but I need to concoct an example to demonstrate this.

Prune skipped_deps from build_dependencies

---

impl/Cargo.lock
impl/Cargo.toml
impl/src/bazel.rs
impl/src/context.rs
impl/src/metadata.rs
impl/src/planning.rs
impl/src/templates/partials/build_script.template
impl/src/templates/partials/rust_binary.template
impl/src/templates/partials/rust_library.template
impl/test_fixtures/metadata.txt

Closes #79.
@acmcarther could you take a look?

Support for Rust editions

---

impl/src/templates/partials/rust_binary.template

Fix other problem in #90 
I'm only 40% confident this works / is the correct thing to do. (ie. i did not build this locally)

sanitize binary's lib dep

---

impl/src/bazel.rs
impl/src/context.rs
impl/src/planning.rs
impl/src/templates/remote_crates.bzl.template
smoke_test/remote/complicated_cargo_library/cargo/Cargo.toml

Fixes https://github.com/google/cargo-raze/issues/101
(and updates a smoke test to use this setting)

Fix output_buildfile_suffix for remote

---

impl/src/templates/partials/build_script.template

Ensure build script genrule uses nested output dir

---

impl/src/templates/partials/build_script.template

cc: @vitalyd 
See also https://github.com/google/cargo-raze/issues/100

Replace build script local=1 with tags=no-sandbox

---

impl/src/bin/cargo-raze.rs

Otherwise it ignores cmd line options

Fix docopt's usage

---

README.md
examples/remote/non_cratesio/README.md
examples/vendored/hello_cargo_library/README.md
examples/vendored/non_cratesio_library/README.md
impl/src/planning.rs
smoke_test/README.md
smoke_test/remote/non_cratesio/README.md
smoke_test/vendored/hello_cargo_library/README.md
smoke_test/vendored/non_cratesio_library/README.md

fixes https://github.com/google/cargo-raze/issues/126

Update docs and impl to refer to cargo vendor instead of cargo-vendor

---

examples/WORKSPACE

Signed-off-by: Gregg Reynolds <601396+mobileink@users.noreply.github.com>

upgrade examples WORKSPACE to latest versions of rules_rust, skylib

---

examples/WORKSPACE
smoke-test.sh

Bump example workspace to latest master

---

impl/src/templates/crate.BUILD.template
impl/src/templates/remote_crates.bzl.template
impl/src/templates/workspace.BUILD.template

To resolve request in https://github.com/google/cargo-raze/issues/196

Add @generated signature to templates

---

impl/src/bin/cargo-raze.rs
impl/src/settings.rs

This change moves the functionality of `load_settings` into the `settings` module so that it can be properly tested.

Formalized 'load_settings' by moving it into the settings module

---

impl/src/lib.rs
impl/src/metadata.rs
impl/src/planning.rs
impl/src/testing.rs

This de-duplicates some test code by adding the common test functions to a module.

Added testing module

---

examples/remote/complicated_cargo_library/cargo/remote/libloading-0.5.2.BUILD.bazel
examples/remote/complicated_cargo_library/cargo/remote/rayon-core-1.8.1.BUILD.bazel
examples/remote/complicated_cargo_library/cargo/remote/time-0.1.44.BUILD.bazel
examples/remote/complicated_cargo_library/cargo/remote/winapi-0.3.9.BUILD.bazel
examples/remote/non_cratesio/cargo/remote/atty-0.2.14.BUILD.bazel
examples/vendored/complicated_cargo_library/cargo/vendor/rayon-core-1.8.1/BUILD.bazel
examples/vendored/complicated_cargo_library/cargo/vendor/time-0.1.44/BUILD.bazel
examples/vendored/complicated_cargo_library/cargo/vendor/winapi-0.3.9/BUILD.bazel
examples/vendored/non_cratesio_library/cargo/vendor/atty-0.2.14/BUILD.bazel
examples/vendored/non_cratesio_library/cargo/vendor/iovec-0.1.4/BUILD.bazel
impl/src/templates/partials/common_attrs.template

platform-specific aliases were missing

---

impl/src/context.rs
impl/src/planning/subplanners.rs

Small cleanup PR as per https://github.com/google/cargo-raze/pull/260#discussion_r508732796

Some small cleanup

---

README.md
examples/WORKSPACE
examples/remote/binary_dependencies/cargo/remote/BUILD.clap-2.33.0.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.clap-2.33.3.bazel
examples/remote/complicated_cargo_library/cargo/remote/BUILD.time-0.1.44.bazel
examples/vendored/complicated_cargo_library/cargo/vendor/time-0.1.44/BUILD.bazel
impl/src/util.rs
smoke-test.sh

Add support for wasm32-wasi target.

---

README.md

Re discussion in https://github.com/google/cargo-raze/issues/289

add default_gen_buildrs to README

---

README.md
examples/WORKSPACE
examples/remote/binary_dependencies/cargo/remote/BUILD.atty-0.2.14.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.clap-2.33.0.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.clap-2.33.3.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.clicolors-control-1.0.1.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.console-0.9.2.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.encode_unicode-0.3.6.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.rand-0.7.3.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.texture-synthesis-0.8.0.bazel
examples/remote/binary_dependencies/cargo/remote/BUILD.texture-synthesis-cli-0.8.0.bazel
examples/remote/complicated_cargo_library/cargo/remote/BUILD.rayon-core-1.8.1.bazel
examples/remote/non_cratesio/cargo/remote/BUILD.atty-0.2.14.bazel
examples/vendored/complicated_cargo_library/cargo/vendor/rayon-core-1.8.1/BUILD.bazel
examples/vendored/non_cratesio_library/cargo/vendor/atty-0.2.14/BUILD.bazel
examples/vendored/non_cratesio_library/cargo/vendor/iovec-0.1.4/BUILD.bazel
impl/src/util.rs
smoke-test.sh

Add support for aarch64-apple-darwin target.

---

CODEOWNERS

This PR adds a file which represents users with merging abilities

Added Code Owners file

---

README.md
impl/src/planning.rs
impl/src/rendering/templates/partials/common_attrs.template
impl/src/settings.rs

https://github.com/bazelbuild/rules_rust/pull/516
This can't be merged until the name is decided and merged into rules_rust.

support compile_data

---

third_party/curl/BUILD.curl.bazel
third_party/iconv/BUILD.iconv.bazel
third_party/libgit2/BUILD.libgit2.bazel
third_party/libssh2/BUILD.libssh2.bazel
third_party/openssl/BUILD.openssl.bazel
third_party/zlib/BUILD.zlib.bazel

This is to be in alignment with https://github.com/bazelbuild/bazel/issues/8622

Replaced `@bazel_tools//src/conditions/...` with `@platforms//...`

---

third_party/pcre/pcre_repositories.bzl

Add SHA256 to @cargo_raze__pcre to silence warnings.

---

impl/src/metadata.rs

Currently we ignore the exit code from this command, swallowing the
error, and typically fail in the subsequent call to `cargo` with a
message along the lines of "No Cargo.lock file was found".
Instead, fatally report the error from `cargo generate-lockfile`.

Report error if lockfile generation fails

---

impl/src/rendering/templates/partials/build_script.template

Include "additional_flags" in build scripts.

---

README.md

main is now the new primary branch.

README: Change branch name from master to main

---

impl/src/context.rs
impl/src/rendering/bazel.rs
impl/src/rendering/templates/partials/build_script.template
impl/src/settings.rs

This solves https://github.com/google/cargo-raze/issues/486

Add tools attribute for CrateSettings

---

README.md

Putting this in as an alternative to #115.

Make note in README more obvious

---

impl/Cargo.lock
impl/Cargo.toml
impl/src/bin/cargo-raze.rs
impl/src/checks.rs
impl/src/context.rs
impl/src/features.rs
impl/src/metadata.rs
impl/src/planning.rs
impl/src/planning/subplanners.rs
impl/src/rendering.rs
impl/src/rendering/bazel.rs
impl/src/settings.rs
impl/src/testing.rs
impl/src/util.rs
third_party/cargo/crates.bzl
third_party/cargo/remote/BUILD.camino-1.0.9.bazel
third_party/cargo/remote/BUILD.cargo_metadata-0.14.0.bazel

Still needs to be DRYed up, especially in the tests. Will close #421 and #510.

Convert all paths to Camino

---

CODEOWNERS

It's been quite a while since I've had bandwidth to review changes here or even context on it's current state. To save myself from notification noise and avoid giving folks false hope for reviews I'd like to be removed from CODEOWNERS.

Remove UebelAndre from CODEOWNERS

---

CODEOWNERS

With a job switch and some other life changes, my meager bandwidth I've provided to this project is non-existant.  That leaves not a lot remaining, so it's probably worth having a conversation about what should happen going forward.

Remove dfreese from CODEOWNERS
